# Site settings
title: silviu's blog
email: zwisgbmdxiyy9qd6v4uw@eml.cc
description: > # this means to ignore newlines until "baseurl:"
  A blog about programming and the pleasure of figuring things out. By Silviu Dan Cacoveanu.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "blog.cacoveanu.com" # the base hostname & protocol for your site
permalink: /:year/:month/:day/:title.html
plugins:
    - jekyll-sitemap
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
highligter: rouge
sass:
  sass_dir: css

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: "post"
