# Site settings
title: heuristics
email: silviu.cacoveanu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog about programming and the pleasure of figuring things out. By Silviu Dan Cacoveanu.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "blog.cacoveanu.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
timezone: Europe/Bucharest
permalink: /:year/:month/:day/:title.html
gems:
    - jekyll-sitemap

# Build settings
markdown: kramdown
highligter: null
sass:
  sass_dir: css
